### ISSUE TITLE
Is it possibleto include new forum/board posts as well?

### ISSUE THREAD

**Issue by jamasi** [egisz/redmine_already_read#1]
I'm not sure if this plugin also displays new posts in the forum/board section of a redmine project already (my Japanese is still not good enough to fully understand the documentation). But it would be great if this functionality could be included as well.

**Comment by egisz** [comment]
Hi,

I'm not original author of this plugin, credit goes to  https://github.com/ameya86/redmine_already_read.
I only modified it to my needs :)

I tried it on Forum module, it does not function there.

**Comment by egisz** [comment]
Double checked Model class AlreadyRead
It clearly defines relations to Issue and User, so it is quite limited to track issues, not forums or other type of documents:

class AlreadyRead < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue
