### ISSUE TITLE
Error when I try to install plugin

### ISSUE THREAD

**Issue by alexander-st** [egisz/redmine_already_read#2]
I was happy to see such a plugin. I was trying to install the plugin as I installed all other plugins, but I receive the following error message:
*\* Invoke db:migrate:plugin (first_time)
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
ArgumentError: wrong number of arguments (1 for 0)
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_already_read/lib/
already_read/issue_patch.rb:24:in `block in <class:Issue>'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations/builder/collection_association.rb:35:in`[]'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations/builder/collection_association.rb:35:in `wrap_block_
extension'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations/builder/collection_association.rb:22:in`build'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/autosave_association.rb:139:in `build'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations/builder/has_many.rb:10:in`build'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations/builder/collection_association.rb:13:in `build'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activerecord-3.2.19/lib
/active_record/associations.rb:1198:in`has_many'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_already_read/lib/
already_read/issue_patch.rb:24:in `<class:Issue>'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_already_read/lib/
already_read/issue_patch.rb:23:in`<top (required)>'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in `require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in`block in require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:236:in `load_dependency'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in`require'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/plugins/redmine_already_read/init
.rb:3:in `<top (required)>'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in`require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in `block in require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:236:in`load_dependency'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in `require'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/lib/redmine/plugin.rb:150:in`blo
ck in load'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in `eac
h'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/lib/redmine/plugin.rb:141:in`loa
d'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/config/initializers/30-redmine.rb
:19:in `<top (required)>'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:245:in`load'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:245:in `block in load'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:236:in`load_dependency'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:245:in `load'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/engine.rb:593:in`block (2 levels) in class:Engine'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/engine.rb:592:in `each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/engine.rb:592:in`block in class:Engine'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/initializable.rb:30:in `instance_exec'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/initializable.rb:30:in`run'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/initializable.rb:55:in `block in run_initializers'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/initializable.rb:54:in`each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/initializable.rb:54:in `run_initializers'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/application.rb:136:in`initialize!'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/railtie/configurable.rb:30:in `method_missing'
C:/Bitnami/redmine-2.6.0-2/apps/redmine/htdocs/config/environment.rb:14:in`<top
 (required)>'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in `require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in`block in require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:236:in `load_dependency'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/activesupport-3.2.19/li
b/active_support/dependencies.rb:251:in`require'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/application.rb:103:in `require_environment!'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/railties-3.2.19/lib/rai
ls/application.rb:305:in`block (2 levels) in initialize_tasks'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:240:in `call'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:240:in`block in execute'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:235:in `each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:235:in`execute'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:179:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchroniz
e'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:172:in `invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:201:in`block in invoke_prerequisites'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:199:in `each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:199:in`invoke_prerequisites'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:178:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchroniz
e'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:172:in `invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:201:in`block in invoke_prerequisites'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:199:in `each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:199:in`invoke_prerequisites'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:178:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/2.0.0/monitor.rb:211:in`mon_synchroniz
e'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:172:in `invoke_with_call_chain'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ta
sk.rb:165:in`invoke'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:156:in `invoke_task'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:112:in`block (2 levels) in top_level'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:112:in `each'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:112:in`block in top_level'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:121:in `run_with_threads'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:106:in`top_level'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:84:in `block in run'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:182:in`standard_exception_handling'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/lib/rake/ap
plication.rb:79:in `run'
C:/Bitnami/redmine-2.6.0-2/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.0/bin/rake:33
:in`<top (required)>'
C:/Bitnami/redmine-2.6.0-2/ruby/bin/rake:23:in `load'
C:/Bitnami/redmine-2.6.0-2/ruby/bin/rake:23:in`<main>'
Tasks: TOP => db:migrate:plugin => redmine:plugins:migrate => environment

**Comment by egisz** [comment]
Hi, 

I tried to update code, it works for me on Redmine trunk version 3.0.3.
Feel free to test on your environment.

Egidijus
